num_classes: &num_classes 2
num_ids: &num_ids 2048
runtime:
  aligned: True
  async_norm: True
  special_bn_init: True
  runner:
    type: motfp16
  model_helper:
    type: mot

tracker:
  type: ma_online
  kwargs:
    output_thr:
      default: 0.5
      MOT20-01: 0.5
      MOT20-02: 0.5
      MOT20-03: 0.5
      MOT20-04: 0.6
      MOT20-05: 0.5
      MOT20-06: 0.3
      MOT20-07: 0.6
      MOT20-08: 0.3

mosaic: &mosaic
  type: mosaic
  kwargs:
    extra_input: True
    tar_size: [896, 1600]
    fill_color: 0
    mosaic_self: False

random_perspective: &random_perspective
  type: random_perspective_yolox
  kwargs:
    degrees: 10.0 # 0.0
    translate: 0.1
    scale: [0.1, 2.0] # 0.5
    shear: 2.0 # 0.0
    perspective: 0.0
    fill_color: 0 # 0
    border: [-448, -800]

augment_hsv: &augment_hsv
  type: augment_hsv
  kwargs:
    hgain: 0.015
    sgain: 0.7
    vgain: 0.4
    color_mode: "BGR"

mixup: &mixup
  type: yolox_mixup_cv2
  kwargs:
    extra_input: True
    input_size: [896, 1600]
    mixup_scale: [0.8, 1.6]
    fill_color: 0

flip: &flip
  type: flip
  kwargs:
    flip_p: 0.5

to_tensor: &to_tensor
  type: custom_to_tensor

train_resize: &train_resize
  type: keep_ar_resize_max
  kwargs:
    # max_size: 1600
    # padding_type: left_top
    # padding_val: 0
    random_size: [20, 36]

test_resize: &test_resize
  type: keep_ar_resize_max
  kwargs:
    max_size: 1600
    # padding_type: left_top
    # padding_val: 0

dataset:
  train:
    dataset:
      type: mot
      kwargs:
        num_classes: *num_classes
        num_ids: *num_ids
        meta_file: /mnt/lustre/share/fengweitao/MOT20/annotations/train_half.json
        image_reader:
          type: fs_opencv
          kwargs:
            image_dir: [/mnt/lustre/share/fengweitao/MOT20/, /]
            color_mode: BGR
        transformer:
          [*mosaic, *random_perspective, *flip, *train_resize, *to_tensor]
    batch_sampler:
      type: base
      kwargs:
        sampler:
          type: dist
          kwargs: {}
        batch_size: 2
  test:
    dataset:
      type: mot
      kwargs:
        num_classes: *num_classes
        meta_file: /mnt/lustre/share/fengweitao/MOT20/annotations/train.json
        image_reader:
          type: fs_opencv
          kwargs:
            image_dir: /
            color_mode: BGR
        transformer: [*test_resize, *to_tensor]
        evaluator:
          type: tracking
          kwargs:
            gt_file: /mnt/lustre/share/fengweitao/MOT20/annotations/train.json
            iou_thresh: 0.5
            num_classes: *num_classes
    batch_sampler:
      type: sequence
      kwargs:
        sampler:
          type: dist_seq
          kwargs: {}
        batch_size: 1
  dataloader:
    type: mot
    kwargs:
      num_workers: 4
      alignment: 32
      worker_init: True
      pad_type: batch_pad
  builder_type: custom

trainer: # Required.
  max_epoch: &max_epoch 40 # total epochs for the training
  save_freq: 5
  test_freq: 5
  only_save_latest: True
  optimizer: # optimizer = SGD(params,lr=0.01,momentum=0.937,weight_decay=0.0005)
    register_type: yolov5
    type: AdamW
    kwargs:
      lr: 6.25e-06
      betas: [0.9, 0.999]
      weight_decay: 0.05 # weight_decay = 0.0005 * batch_szie / 64
  lr_scheduler:
    lr_register_type: yolox_base
    warmup_epochs: 1 # set to be 0 to disable warmup. When warmup,  target_lr = init_lr * total_batch_size
    warmup_type: yolox_cos
    type: YoloXCosineLR
    kwargs:
      T_max: *max_epoch
      min_lr_scale: 0.05
      no_aug_epoch: &no_aug_epoch 10

saver:
  save_dir: checkpoints/sqga_large_mot_fp16
  pretrain_model: pretrained/yolox_large_adamw.mot.pth
  results_dir: results_dir/sqga_large_mot_fp16
  auto_resume: True
  save_result: True

hooks:
  - type: train_val_logger
    kwargs:
      freq: 10
      skip_first_k: 5
      logdir: log/sqga_large_mot_fp16
  - type: yolox_mot_noaug
    kwargs:
      no_aug_epoch: *no_aug_epoch
      max_epoch: *max_epoch
      transformer: [*augment_hsv, *flip, *train_resize, *to_tensor]
  - type: auto_save_best

ema:
  enable: True
  ema_type: exp
  kwargs:
    decay: 0.9998

Bn: &Bn
  type: pt_sync_bn
  kwargs:
    bn_group_size: 4

net:
  - name: backbone
    type: mot_wrapper
    kwargs:
      cfg:
        type: yolox_l
        kwargs:
          out_layers: [2, 3, 4]
          out_strides: [8, 16, 32]
          normalize: *Bn
          act_fn: { "type": "Silu" }
  - name: neck
    prev: backbone
    type: mot_wrapper
    kwargs:
      cfg:
        type: YoloxPAFPN
        kwargs:
          depth: &depth 1.0
          out_strides: [8, 16, 32]
          act_fn: { "type": "Silu" }
          normalize: *Bn
  - name: roi_head
    prev: neck
    type: mot_wrapper
    kwargs:
      cfg:
        type: YoloXHeadwID
        kwargs:
          num_classes: *num_classes # number of classes including backgroudn. for rpn, it's 2; for RetinaNet, it's 81
          num_ids: *num_ids
          width: 1.0
          num_point: &dense_points 1
          act_fn: { "type": "Silu" }
          normalize: *Bn
  - name: relation_module
    prev: roi_head
    type: relation_yolox
    kwargs:
      num_to_refine: 150
      num_as_ref: 40
      relation_cfgs:
        - type: sqga
          index: 0
          kwargs:
            beta: 0.1
            np_ratio: 3
            loss:
              type: sigmoid_cross_entropy
          loss:
            type: sigmoid_cross_entropy
        - type: sqga
          index: 2
          kwargs:
            beta: 0.1
            np_ratio: 3
            loss:
              type: sigmoid_cross_entropy
          loss:
            type: sigmoid_cross_entropy
      yolox_kwargs:
        num_classes: *num_classes # number of classes including backgroudn. for rpn, it's 2; for RetinaNet, it's 81
        num_ids: *num_ids
        cfg:
          loc_loss:
            type: iou_loss
            kwargs:
              loss_type: square_iou
              loss_weight: 5.0
          cls_loss:
            type: sigmoid_cross_entropy
          obj_loss:
            type: sigmoid_cross_entropy
          id_loss:
            type: sigmoid_cross_entropy
          anchor_generator:
            type: fcos # yolox
            kwargs:
              dense_points: *dense_points
              center: False
          roi_supervisor:
            type: ota_w_id
            kwargs:
              num_classes: *num_classes
              num_ids: *num_ids
              matcher:
                type: ota_w_id
                kwargs:
                  num_classes: *num_classes
          roi_predictor:
            type: yolox_w_id
            kwargs:
              num_classes: *num_classes
              pre_nms_score_thresh: 0.001
              nms:
                type: naive
                nms_iou_thresh: 0.7
